### ISSUE TITLE
Setting up the network connection  error

### ISSUE THREAD

**Issue by godwei123** [firmadyne/firmadyne#164]
Vmware+Ubuntu 18.04.5LTS +AMD 64

```
[+] Firmware: DIR823GA1_FW102B03.bin
[+] Extracting the firmware...
[+] Image ID: 2
[+] Identifying architecture...
[+] Architecture: mipsel
[+] Building QEMU disk image...
[+] Setting up the network connection, please standby...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 150, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 465, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 155, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fat.py", line 170, in <module>
    main()
  File "fat.py", line 165, in main
    infer_network(arch, image_id, qemu_dir)
  File "fat.py", line 111, in infer_network
    child.expect_exact("Interfaces:", timeout=None)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7ffac1e47da0>
command: /home/gw/firmware-analysis-toolkit/firmadyne/scripts/inferNetwork.sh
args: ['/home/gw/firmware-analysis-toolkit/firmadyne/scripts/inferNetwork.sh', '2', 'mipsel']
buffer (last 100 chars): b''
before (last 100 chars): b'nitor unix:/tmp/qemu.2,server,nowait: Failed to unlink socket /tmp/qemu.2: Operation not permitted\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 23873
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "b'Interfaces:'"
```

**Comment by ddcc** [comment]
Doesn't look like a bug in firmadyne. I have no idea how Firmware Analysis Toolkit works, you should report any problems with that to them.
