### ISSUE TITLE
Password Authentication Failed

### ISSUE THREAD

**Issue by flamecopper** [firmadyne/firmadyne#193]
Hi I have tried all I can already still password authentication failed.
Do advise.
```
sudo python3 sources/extractor/extractor.py -b Netgear -sql 127.0.0.1 -np -nk "WNAP320 Firmware Version 2.0.3.zip" images
Traceback (most recent call last):
  File "sources/extractor/extractor.py", line 732, in <module>
    main()
  File "sources/extractor/extractor.py", line 729, in main
    extract.extract()
  File "sources/extractor/extractor.py", line 191, in extract
    self._extract_item(item)
  File "sources/extractor/extractor.py", line 199, in _extract_item
    ExtractionItem(self, path, 0).extract()
  File "sources/extractor/extractor.py", line 226, in __init__
    self.database = psycopg2.connect(database="firmware",
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "firmadyne"
connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "firmadyne
```

**Comment by ddcc** [comment]
This is the password you chose while setting up the database: https://github.com/firmadyne/firmadyne#database

You can always change it to something else using the postgres tool.
