### ISSUE TITLE
Network is created with br0', '192.168.0.1' and 'br1', '192.168.7.1'. But the application is not hosted in the same address.

### ISSUE THREAD

**Issue by raviwithu** [firmadyne/firmadyne#20]
Enter the name or absolute path of the firmware you want to analyse : /root/Desktop/IOT/SecTu/Dlink/DIR880A1_FW103WWb11_f41b.bin
Enter the brand of the firmware : Dlink
/root/Desktop/IOT/SecTu/Dlink/DIR880A1_FW103WWb11_f41b.bin
Now going to extract the firmware. Hold on..
/root/tools/firmadyne/sources/extractor/extractor.py -b Dlink -sql 127.0.0.1 -np -nk "/root/Desktop/IOT/SecTu/Dlink/DIR880A1_FW103WWb11_f41b.bin" images 
test
The database ID is 1
Getting image type
Password for user firmadyne: 
Found image type of  armel
Putting information to database
Traceback (most recent call last):
  File "/root/tools/firmadyne/scripts/tar2db.py", line 100, in <module>
    main()
  File "/root/tools/firmadyne/scripts/tar2db.py", line 97, in main
    process(iid, infile)
  File "/root/tools/firmadyne/scripts/tar2db.py", line 77, in process
    insertObjectToImage(iid, file2oid, links, cur)
  File "/root/tools/firmadyne/scripts/tar2db.py", line 57, in insertObjectToImage
    for x in files2oids])
psycopg2.IntegrityError: duplicate key value violates unique constraint "object_to_image_oid_iid_filename_key"
DETAIL:  Key (oid, iid, filename)=(1, 1, /htdocs/phplib/fatlady/SMS.php) already exists.

Tar2DBb''
Creating Image
Executing command 

sudo /root/tools/firmadyne/scripts/makeImage.sh 1
Password for user firmadyne: 
mke2fs 1.43.3 (04-Sep-2016)
/fixImage.sh: line 30: can't create /etc/passwd: nonexistent directory
device-mapper: remove ioctl on loop0p1 failed: Device or resource busy
Make Image output b"Querying database for architecture... armel\n----Running----\n----Copying Filesystem Tarball----\n----Creating QEMU Image----\nFormatting '/root/tools/firmadyne/scratch//1//image.raw', fmt=raw size=1073741824\n----Creating Partition Table----\n\nWelcome to fdisk (util-linux 2.28.2).\nChanges will remain in memory only, until you decide to write them.\nBe careful before using the write command.\n\nDevice does not contain a recognized partition table.\nCreated a new DOS disklabel with disk identifier 0x024286e8.\n\nCommand (m for help): Created a new DOS disklabel with disk identifier 0x5c31d996.\n\nCommand (m for help): Partition type\n   p   primary (0 primary, 0 extended, 4 free)\n   e   extended (container for logical partitions)\nSelect (default p): Partition number (1-4, default 1): First sector (2048-2097151, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-2097151, default 2097151): \nCreated a new partition 1 of type 'Linux' and of size 1023 MiB.\n\nCommand (m for help): The partition table has been altered.\nSyncing disks.\n\n----Mounting QEMU Image----\nadd map loop0p1 (254:0): 0 2095104 linear 7:0 2048\n----Creating Filesystem----\nDiscarding device blocks:   4096/261888\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08             \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08done                            \nCreating filesystem with 261888 4k blocks and 65536 inodes\nFilesystem UUID: 38d55df2-d3b5-448e-b48f-af4d7993d3ed\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376\n\nAllocating group tables: 0/8\x08\x08\x08   \x08\x08\x08done                            \nWriting inode tables: 0/8\x08\x08\x08   \x08\x08\x08done                            \nWriting superblocks and filesystem accounting information: 0/8\x08\x08\x08   \x08\x08\x08done\n\n----Making QEMU Image Mountpoint----\n----Mounting QEMU Image Partition 1----\n----Extracting Filesystem Tarball----\n----Creating FIRMADYNE Directories----\n----Patching Filesystem (chroot)----\nCreating /etc/TZ!\nCreating /etc/hosts!\nCreating /etc/passwd!\nRemoving /etc/scripts/sys_resetbutton!\n----Setting up FIRMADYNE----\n----Unmounting QEMU Image----\nloop deleted : /dev/loop0\n"
Everything is done for the image id 1
Setting up the network connection
Password for user firmadyne: 
qemu-system-arm: terminating on signal 2 from pid 13316
b"Querying database for architecture... armel\nRunning firmware 1: terminating after 60 secs...\nInferring network...\nInterfaces: [('br0', '192.168.0.1'), ('br1', '192.168.7.1')]\nDone!\n"
Running the firmware finally : 
Enter the name or absolute path of the firmware you want to analyse : /root/Desktop/IOT/SecTu/Dlink/DIR880A1_FW103WWb11_f41b.bin
Enter the brand of the firmware : Dlink
/root/Desktop/IOT/SecTu/Dlink/DIR880A1_FW103WWb11_f41b.bin
Now going to extract the firmware. Hold on..
/root/tools/firmadyne/sources/extractor/extractor.py -b Dlink -sql 127.0.0.1 -np -nk "/root/Desktop/IOT/SecTu/Dlink/DIR880A1_FW103WWb11_f41b.bin" images 
test
The database ID is 1
Getting image type
Password for user firmadyne: 
Found image type of  armel
Putting information to database
Traceback (most recent call last):
  File "/root/tools/firmadyne/scripts/tar2db.py", line 100, in <module>
    main()
  File "/root/tools/firmadyne/scripts/tar2db.py", line 97, in main
    process(iid, infile)
  File "/root/tools/firmadyne/scripts/tar2db.py", line 77, in process
    insertObjectToImage(iid, file2oid, links, cur)
  File "/root/tools/firmadyne/scripts/tar2db.py", line 57, in insertObjectToImage
    for x in files2oids])
psycopg2.IntegrityError: duplicate key value violates unique constraint "object_to_image_oid_iid_filename_key"
DETAIL:  Key (oid, iid, filename)=(1, 1, /htdocs/phplib/fatlady/SMS.php) already exists.

Tar2DBb''
Creating Image
Executing command 

sudo /root/tools/firmadyne/scripts/makeImage.sh 1
Password for user firmadyne: 
mke2fs 1.43.3 (04-Sep-2016)
/fixImage.sh: line 30: can't create /etc/passwd: nonexistent directory
device-mapper: remove ioctl on loop0p1 failed: Device or resource busy
Make Image output b"Querying database for architecture... armel\n----Running----\n----Copying Filesystem Tarball----\n----Creating QEMU Image----\nFormatting '/root/tools/firmadyne/scratch//1//image.raw', fmt=raw size=1073741824\n----Creating Partition Table----\n\nWelcome to fdisk (util-linux 2.28.2).\nChanges will remain in memory only, until you decide to write them.\nBe careful before using the write command.\n\nDevice does not contain a recognized partition table.\nCreated a new DOS disklabel with disk identifier 0x024286e8.\n\nCommand (m for help): Created a new DOS disklabel with disk identifier 0x5c31d996.\n\nCommand (m for help): Partition type\n   p   primary (0 primary, 0 extended, 4 free)\n   e   extended (container for logical partitions)\nSelect (default p): Partition number (1-4, default 1): First sector (2048-2097151, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-2097151, default 2097151): \nCreated a new partition 1 of type 'Linux' and of size 1023 MiB.\n\nCommand (m for help): The partition table has been altered.\nSyncing disks.\n\n----Mounting QEMU Image----\nadd map loop0p1 (254:0): 0 2095104 linear 7:0 2048\n----Creating Filesystem----\nDiscarding device blocks:   4096/261888\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08             \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08done                            \nCreating filesystem with 261888 4k blocks and 65536 inodes\nFilesystem UUID: 38d55df2-d3b5-448e-b48f-af4d7993d3ed\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376\n\nAllocating group tables: 0/8\x08\x08\x08   \x08\x08\x08done                            \nWriting inode tables: 0/8\x08\x08\x08   \x08\x08\x08done                            \nWriting superblocks and filesystem accounting information: 0/8\x08\x08\x08   \x08\x08\x08done\n\n----Making QEMU Image Mountpoint----\n----Mounting QEMU Image Partition 1----\n----Extracting Filesystem Tarball----\n----Creating FIRMADYNE Directories----\n----Patching Filesystem (chroot)----\nCreating /etc/TZ!\nCreating /etc/hosts!\nCreating /etc/passwd!\nRemoving /etc/scripts/sys_resetbutton!\n----Setting up FIRMADYNE----\n----Unmounting QEMU Image----\nloop deleted : /dev/loop0\n"
Everything is done for the image id 1
Setting up the network connection
Password for user firmadyne: 
qemu-system-arm: terminating on signal 2 from pid 13316
b"Querying database for architecture... armel\nRunning firmware 1: terminating after 60 secs...\nInferring network...\nInterfaces: [('br0', '192.168.0.1'), ('br1', '192.168.7.1')]\nDone!\n"
Running the firmware finally :

**Comment by ddcc** [comment]
I'm not quite sure what the problem is, and the output you pasted isn't very readable. Is this a clean database? The output suggests that it already has entries loaded from a previous extraction. Also, I don't recognize some of the strings in your output; they're not something that the tool should print.
