### ISSUE TITLE
fixImage.sh: line 30: can't create /etc/passwd: nonexistent directory

### ISSUE THREAD

**Issue by tohaikmeng** [firmadyne/firmadyne#69]
Hi, 

I am using OIT vm but encounter the following issue:
"/fixImage.sh: line 30: can't create /etc/passwd: nonexistent directory"

--------------------------- Console output below ----------------------------------
[sudo] password for oit: 
Querying database for architecture... Password for user firmadyne: 
mipsel
----Running----
----Copying Filesystem Tarball----
----Creating QEMU Image----
Formatting '/home/oit/tools/firmadyne//scratch//1//image.raw', fmt=raw size=1073741824 
----Creating Partition Table----
Device contains neither a valid DOS partition table, nor Sun, SGI or OSF disklabel
Building a new DOS disklabel with disk identifier 0x5d122db4.
Changes will remain in memory only, until you decide to write them.
After that, of course, the previous content won't be recoverable.

Warning: invalid flag 0x0000 of partition table 4 will be corrected by w(rite)

Command (m for help): Building a new DOS disklabel with disk identifier 0x5ee1eba9.
Changes will remain in memory only, until you decide to write them.
After that, of course, the previous content won't be recoverable.

Warning: invalid flag 0x0000 of partition table 4 will be corrected by w(rite)

Command (m for help): Partition type:
   p   primary (0 primary, 0 extended, 4 free)
   e   extended
Select (default p): Partition number (1-4, default 1): First sector (2048-2097151, default 2048): Using default value 2048
Last sector, +sectors or +size{K,M,G} (2048-2097151, default 2097151): Using default value 2097151

Command (m for help): The partition table has been altered!

Syncing disks.
----Mounting QEMU Image----
add map loop0p1 (252:0): 0 2095104 linear /dev/loop0 2048
----Creating Filesystem----
mke2fs 1.42.9 (4-Feb-2014)
Discarding device blocks: done                            
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
65536 inodes, 261888 blocks
13094 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=268435456
8 block groups
32768 blocks per group, 32768 fragments per group
8192 inodes per group
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376

Allocating group tables: done                            
Writing inode tables: done                            
Writing superblocks and filesystem accounting information: done

----Making QEMU Image Mountpoint----
----Mounting QEMU Image Partition 1----
----Extracting Filesystem Tarball----
----Creating FIRMADYNE Directories----
----Patching Filesystem (chroot)----
Creating /etc/TZ!
Creating /etc/hosts!
Creating /etc/passwd!
/fixImage.sh: line 30: can't create /etc/passwd: nonexistent directory
Warning: Recreating device nodes!
Removing /etc/scripts/sys_resetbutton!
----Setting up FIRMADYNE----
----Unmounting QEMU Image----
loop deleted : /dev/loop0

**Comment by ddcc** [comment]
I'm not sure what OIT is. Some errors are normal. Does it actually emulate and connect over the network?

**Comment by tohaikmeng** [comment]
Hi Dominic,

thanks for prompt reply, it does not emulate and no interface. do you know why?

I suspect this line :/fixImage.sh: line 30: can't create /etc/passwd: nonexistent directory

--------------------------- Console output below ----------------------------------
/fixImage.sh: line 30: can't create /etc/passwd: nonexistent directory
Please check the makeImage function
Everything is done for the image id 1
Setting up the network connection
Password for user firmadyne: 
qemu: terminating on signal 2 from pid 9695
Querying database for architecture... mipsel
Running firmware 1: terminating after 60 secs...
Inferring network...
Interfaces: []
Done!

Running the firmware finally : 
sudo: /home/oit/tools/firmadyne/scratch/1/run.sh: command not found
Traceback (most recent call last):
  File "./fat.py", line 113, in <module>
    main()
  File "./fat.py", line 109, in main
    final_run(image_id)
  File "./fat.py", line 89, in final_run
    print subprocess.check_output(final_run_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'sudo /home/oit/tools/firmadyne/scratch/1/run.sh' returned non-zero exit status 1

**Comment by ddcc** [comment]
I doubt the problem is with fixImage.sh, the underlying problem is that the network configuration is unable to be inferred, so no emulation run.sh script is generated. This is mentioned in the [FAQ entry](https://github.com/firmadyne/firmadyne#runsh-is-not-generated). You can post the contents of qemu.initial.serial.log, but I can only provide suggestions and this will most likely involve manual debugging on your behalf.
